module "rds" {
  source                      = "github.com/mitlibraries/tf-mod-rds?ref=0.12"
  name                        = "${module.label.name}-rds"
  engine                      = var.rds_engine
  engine_version              = var.rds_maj_eng_ver
  instance_class              = var.rds_inst_class
  allocated_storage           = var.rds_storage
  database_name               = var.rds_db_name
  database_user               = var.rds_username
  database_password           = var.rds_password
  database_port               = var.rds_port
  db_parameter_group          = var.rds_param_grp
  maintenance_window          = var.rds_maint_win
  backup_window               = var.rds_backup_win
  backup_retention_period     = var.rds_backup_retain
  vpc_id                      = module.shared.vpc_id
  subnet_ids                  = module.shared.private_subnets
  security_group_ids          = [aws_security_group.default.id]
  major_engine_version        = var.rds_eng_ver
  allow_major_version_upgrade = var.rds_maj_upgrade
  apply_immediately           = var.rds_apply_immediately
  dns_zone_id                 = module.shared.private_zoneid
}
